apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wrrv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0067-tenant/tkrw-pr712-0075-0067-app/devfile-sample-wrrv@sha256:09f97b770422bfdd9c51d15af1223dbff141782c900e00892e16c438f1e4c358
        name: my-nodejs
        resources: {}
status: {}
